flipflop_top:
    jg jg_fpv.tcl -allow_unsupported_OS -define FLIPFLOP_TOP 1&

program_counter_top:
    jg jg_fpv.tcl -allow_unsupported_OS -define PROGRAM_COUNTER_TOP 1&

uc_8bits_top:
    jg jg_fpv.tcl -allow_unsupported_OS -define UC_8BITS_TOP 1&

alu_top:
    jg jg_fpv.tcl -allow_unsupported_OS -define ALU_TOP 1&

gpio_demux_top:
    jg jg_fpv.tcl -allow_unsupported_OS -define GPIO_DEMUX_TOP 1&

bus_shift_top:
    jg jg_fpv.tcl -allow_unsupported_OS -define BUS_SHIFT_TOP 1&

control_unit_top:
    jg jg_fpv.tcl -allow_unsupported_OS -define CONTROL_UNIT_TOP 1&

sram_64x8_top:
    jg jg_fpv.tcl -allow_unsupported_OS -define SRAM_64X8_TOP 1&

shift_top:
    jg jg_fpv.tcl -allow_unsupported_OS -define SHIFT_TOP 1&

